Startup informers rbac
java-operator-sdk/java-operator-sdk pull request #1571
Opened 2022-10-26 09:26 UTC by csviri

2022-10-26 13:20 UTC, csviri commented
Note that tried to make a distinction of integration tests based on Tag but there were issues with it in surefire plugin

2022-10-26 15:02 UTC, metacosm requested changes

2022-10-27 07:15 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java
> +  private Boolean stopOnInformerErrorDuringStartup;
yep, it's to check if it is set or not

2022-10-27 07:45 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
> +        if (configService.stopOnInformerErrorDuringStartup()) {
It retries, with exponential backoff forever.

2022-10-27 07:46 UTC, csviri commented on operator-framework-core/src/test/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerEventSourceTest.java
> +      assertThrows(RuntimeException.class, () -> informerEventSource.start());
added.

2022-10-27 08:27 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
> +        if (configService.stopOnInformerErrorDuringStartup()) {
Maybe we should log something to say that that's what's going to happen?

2022-10-27 08:29 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
> +        if (configService.stopOnInformerErrorDuringStartup()) {
yep we can too, although fabric also does logging

2022-10-27 08:31 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/informer/InformerWrapper.java
> +        if (configService.stopOnInformerErrorDuringStartup()) {
updated

2022-10-27 08:52 UTC, metacosm approved these changes

2022-10-27 08:57 UTC, merged