feat: runtime info for health probes
java-operator-sdk/java-operator-sdk pull request #1594
Opened 2022-11-08 12:56 UTC by csviri

2022-11-08 14:25 UTC, csviri commented
closes #1340 
closes #1412

2022-11-22 15:51 UTC, metacosm requested changes
LGTM apart from documentation.

2022-11-22 15:51 UTC, metacosm commented on docs/documentation/features.md
> +is accessed. You can access mainly health information of event sources. Based on that liveness probes can be registered
This sentence doesn't work.

2022-11-23 08:45 UTC, metacosm approved these changes

2022-11-23 11:40 UTC, merged