feat: workflows can be created without associated dependent resource
java-operator-sdk/java-operator-sdk pull request #1632
Opened 2022-11-25 18:41 UTC by metacosm

- feat: make it possible to control how workflows are created
- refactor: rename DependentResourceNode to DefaultDependentResourceNode
- refactor: remove unneeded methods on Workflow
- refactor: extract DependentResourceNode interface and use it
- feat: workflows can be created without associated dependent resource

2022-11-29 10:01 UTC, csviri approved these changes
Apart from little naming LGTM

2022-12-02 08:49 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +  static boolean canDeleteIfAble(DependentResource<?, ?> dependentResource) {
What would you name it?

2022-12-02 09:12 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +  static boolean canDeleteIfAble(DependentResource<?, ?> dependentResource) {
`deletable`?

2022-12-02 09:18 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +  static boolean canDeleteIfAble(DependentResource<?, ?> dependentResource) {
Also problem here is that GarbageCollected is only applicatble for KubernetesDependentResource, so it is little smelly that it's on this layer.

2022-12-02 09:20 UTC, csviri requested changes

2022-12-02 09:22 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +  static boolean canDeleteIfAble(DependentResource<?, ?> dependentResource) {
Yeah, wasn't too sure where to put it but the problem is that the code in this method was spread at different spots that didn't have anything to do with `KubernetesDependentResource` either so it's less smelly now than it was.

2022-12-02 09:30 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +    return dependentResource instanceof Deleter && !(dependentResource instanceof GarbageCollected);
This isn't the case in the tests, though…

2022-12-02 09:43 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +    return dependentResource instanceof Deleter && !(dependentResource instanceof GarbageCollected);
Hmm where exactly?

2022-12-02 11:21 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/dependent/DependentResource.java
> +    return dependentResource instanceof Deleter && !(dependentResource instanceof GarbageCollected);
See https://github.com/java-operator-sdk/java-operator-sdk/pull/1632/commits/0a1a381d48dc5d3a426d7a8ad7c5b468be3a2061

2022-12-02 11:45 UTC, csviri approved these changes
LGTM

2022-12-02 11:49 UTC, merged