feat: bounded cache (variant 2)
java-operator-sdk/java-operator-sdk pull request #1718
Opened 2023-01-13 08:14 UTC by csviri

2023-02-20 19:59 UTC, metacosm requested changes

2023-02-21 10:04 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/cache/KubernetesResourceFetcher.java
> +   * This would not be needed
this was a leftover, removed.

2023-02-21 10:05 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
> +   * See <a href=
updated.

2023-02-21 11:21 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/cache/BoundedItemStore.java
> +        existingMinimalResources.remove(key);
will revisit this, came to my mind that there an case, where the current impl might be a problem of this method

2023-02-21 12:01 UTC, metacosm approved these changes

2023-02-21 12:01 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/cache/BoundedItemStore.java
> +        existingMinimalResources.remove(key);
made an update for this, to be absolutely safe

2023-02-21 12:02 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/cache/BoundedItemStore.java
> +          existingMinimalResources.remove(key);
I still think that `actual` should be removed from `cache` as well.

2023-02-21 12:04 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
> +   * Replaces the item store in informer. See underling <a href=
```suggestion
   * Replaces the item store in informer. See underlying <a href=
```

2023-02-21 12:04 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ResourceConfiguration.java
> +   * The main goal, is to be able to use limited caches.
```suggestion
   * The main goal is to be able to use limited caches.
```

2023-02-21 15:31 UTC, merged