Graceful shutdown
java-operator-sdk/java-operator-sdk pull request #1735
Opened 2023-01-25 15:00 UTC by csviri

2023-01-25 15:32 UTC, csviri commented
This might deserve also an end to end test, to showcase, how SIGTERM and SIGKILL works in pods. WDYT @metacosm  ?

2023-01-25 15:34 UTC, metacosm requested changes

2023-01-25 15:43 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
> +        log.debug("Event processor not running skipping resource processing: {}", resourceID);
yes, wonder how the test passed, will check

2023-01-25 15:50 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
> +  @Deprecated(forRemoval = true)
added

2023-01-26 09:51 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/EventProcessor.java
> +        log.debug("Event processor not running skipping resource processing: {}", resourceID);
fixed the unit test, was not trivial, wonder if we should refactor this in the future.

2023-01-30 13:08 UTC, metacosm reviewed
LGTM apart from question regarding deprecation of termination timeout

2023-01-30 13:34 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java
> +   * @deprecated use {@link io.javaoperatorsdk.operator.Operator#stop(Duration)} instead. Where the
I would prefer to have a single way to configure this, and it is much simpler with the parameters. Keeping this, would be two way to do the same thing.

2023-02-07 13:47 UTC, metacosm approved these changes

2023-02-07 13:50 UTC, merged