feat: improved per resource polling
java-operator-sdk/java-operator-sdk pull request #1826
Opened 2023-03-22 07:52 UTC by csviri

2023-03-26 14:36 UTC, metacosm requested changes

2023-03-26 14:36 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
> +// todo check docs
This should be removed.

2023-03-26 14:36 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
> +     * expected to change it's state frequently. For example an AWS RDS instance is up and running,
```suggestion
     * expected to change its state frequently. For example an AWS RDS instance is up and running,
```

2023-03-27 06:53 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/polling/PerResourcePollingEventSource.java
> +// todo check docs
removed

2023-03-27 08:28 UTC, metacosm approved these changes

2023-03-27 10:40 UTC, merged