matchers ignore list
java-operator-sdk/java-operator-sdk pull request #1880
Opened 2023-05-02 12:24 UTC by csviri

2023-05-02 15:20 UTC, csviri commented
@metacosm in a separate PR will change the behavior, in a way that Kubernetes Service will be a special case, but the default behavior will use equality matcher.

2023-05-03 13:00 UTC, metacosm requested changes

2023-05-03 13:37 UTC, csviri commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
> +    return match(desired, actualResource, false, false, false);
but that did not change the behavior I believe

2023-05-03 15:39 UTC, metacosm commented on operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java
> +    return match(desired, actualResource, false, false, false);
One parameter got changed from `true` to `false`. If changing this doesn't change the behavior, then what's the point of the parameter? 😄 
More seriously, though, before this commit the metadata was considered, now it's not anymore so the javadoc is not correct anymore with respect to the implementation.

2023-05-04 12:51 UTC, metacosm approved these changes

2023-05-04 13:05 UTC, merged